### ISSUE TITLE
how to use this in vueify?

### ISSUE THREAD

**Issue by spurdow** [egoist/vue-timeago#12]
how to use this in vueify?

**Comment by egoist** [comment]
https://github.com/egoist/vue-timeago#usage

Is something wrong?

**Comment by spurdow** [comment]
its just too much short cut, Im still new to vue js and vueify but i think I understand how to do it in vueify now
```javacsript
<script>
    const timeago = require('vue-timeago');

    module.exports = {
       components: {
            timeago
        }
    }

</script>
```

**Comment by egoist** [comment]
you should register the component globally instead:

```js
const VueTimeago = require('vue-timeago')

Vue.use(VueTimeago, {/* config */))
```
