### ISSUE TITLE
Importing locale in Webpack  

### ISSUE THREAD

**Issue by cretueusebiu** [egoist/vue-timeago#14]
When I'm using Webpack (via [Laravel Elixir](https://github.com/laravel/elixir)) the locale file is not imported.

How about using `export default {}` for the locales ?

**Comment by egoist** [comment]
why it's not imported? did you `require` it and add a json loader?

**Comment by cretueusebiu** [comment]
Yes it works with json loader, but I thought it would be easier if  the locales where exported so you don't have to use the `json!` prefix.

**Comment by egoist** [comment]
You don't have to add a `json!` prefix
