### ISSUE TITLE
Weird error 

### ISSUE THREAD

**Issue by Masterchoc** [egoist/vue-timeago#16]
Hello,

i just tried to use the library and follow the example just as in the example, and impossible after 2 days...
I didnt try to update the library, but something is wrong with it.

Here the error i got : 
`[Vue warn]: Error when evaluating expression "function (){var e=this.now/1e3-this.since/1e3;if(this.maxTime&&e>this.maxTime)return clearInterval(this.interval),this.format?this.format(this.since):r(this.since);var t=e<=5?n("just now",this.currentLocale[0]):e<s?n(e,this.currentLocale[1]):e<a?n(e/s,this.currentLocale[2]):e<o?n(e/a,this.currentLocale[3]):e<u?n(e/o,this.currentLocale[4]):e<l?n(e/u,this.currentLocale[5]):e<d?n(e/l,this.currentLocale[6]):n(e/d,this.currentLocale[7]);return t}": TypeError: Cannot read property 'replace' of undefined (found in component: <timeago>)`

I still can't understand what is wrong... i checked all the parameters i send to the component, and even convert my datetime into timestamp... but nothing...

It's very boring, especially for a simple component like this...

**Comment by egoist** [comment]
Can you provide the steps to reproduce or a JSBin link?

**Comment by Masterchoc** [comment]
Ok, i just attempted to re-create the bug on pastebin, but i cannot.
But, i found where the original error came from : 

`locales: {
    'en-US': require('vue-timeago/locales/en-US.json')
  }`

In the example we go this lines, which i copy/pasted without think, but when i use in code, it look like the require is not working at all, but when i use directly the array in the config it works, example : 

`Vue.use(VueTimeago, {
    name: 'timeago',
    locale: 'en-US',
    locales: {
        'en-US': [
            "just now",
            ["%s second ago", "%s seconds ago"],
            ["%s minute ago", "%s minutes ago"],
            ["%s hour ago", "%s hours ago"],
            ["%s day ago", "%s days ago"],
            ["%s week ago", "%s weeks ago"],
            ["%s month ago", "%s months ago"],
            ["%s year ago", "%s years ago"]
        ]
    }
});`

So maybe it comes from babel and webpack ? Or maybe just turn the locales files into a .js, and export the array ?

I dont really know why this is happening, but this is the only infos i get for now.

Thanks god, it's working now :)

**Comment by egoist** [comment]
Did you add a json-loader?

If something goes with your webpack there will be errors reported in the terminal.

If we just export the locals as an object in a JS file it would be hard to use them directly in browser.

**Comment by egoist** [comment]
It sounds not bad placing locals in a .js file, I'll try that later, thx.

**Comment by cyrrill** [comment]
Just ran into this issue, and @Masterchoc 's solution worked for me, thanks!

**Comment by ghprod** [comment]
@Masterchoc solution worked for me too .. thanks

**Comment by kaankilic** [comment]
@Masterchoc solution worked on my project also.

**Comment by khalilst** [comment]
Where's the @Masterchoc soution? It was a delete message? 
I have this problem, what was that solution?
