### ISSUE TITLE
NaN year ago error on iPhone

### ISSUE THREAD

**Issue by dragonfire1119** [egoist/vue-timeago#22]
I'm using a iPhone & it's working on desktop but not iPhone browser it's just showing NaN year ago. Not sure how to debug the mobile browser with vue.js?

**Comment by egoist** [comment]
You can use safari on Mac to debug in an iOS emulator, I think it's related to an issue with `new.Date` on iOS, will fix it later. 😳

**Comment by dragonfire1119** [comment]
@egoist Thanks for the quick reply. Is there anyway to show a static value when this isn't working?

**Comment by egoist** [comment]
Yep, i think it could be fixed.

**Comment by dragonfire1119** [comment]
@egoist Ok cool. I'm also using Iso8601 for the time. Is that the right format to use?

**Comment by dragonfire1119** [comment]
@egoist Changed to RFC2822 formatting & it works now :)

**Comment by jaketoolson** [comment]
I'm having the same error, it's not clear to me what the fix is @dragonfire1119 @egoist

**Comment by dragonfire1119** [comment]
@jaketoolson Change you formatting time to RFC2822. Example if your using Carbon it would be.

```
\Carbon\Carbon::now()->toRfc822String();
```

**Comment by Leshgan** [comment]
So will it fix or not?

**Comment by egoist** [comment]
@Leshgan see the replies above, not really a bug.

**Comment by R4wizard** [comment]
Although this isn't technically a bug, I believe this plugin could provide more support for custom date formatting. This could be as simple as accepting a 'dateFormat' parameter (i.e.   dateFormat: date => moment(date, 'YYYY-MM...').toDate()   ).

This would avoid me having to do this nasty fix I've included below for anybody else who comes across the same issue:

```js
import VueTimeago from 'vue-timeago';
Vue.use(VueTimeago, {
	name:    'timeago',
	locale:  'en-GB',
	locales: {'en-GB': require('vue-timeago/locales/en-GB.json')}
});
Vue.component("timeago").options.render = function(h) {
	// this hack allows us to use our existing date formats, converting them briefly beforehand.
	let date = this.since.substr(0, 19);
	date = moment(date, 'YYYY-MM-DD HH:MM:SS').toDate();
	return h(
		'time',
		{
			attrs: {
				datetime: date,
				title: this.timeForTitle
			}
		},
		this.timeago
	);
};
```

The fix I suggest would be as simple as doing what I've done there but instead checking for the function parameter and using it if existing.

Thoughts? I can prepare a patch if needed.

**Comment by daixujie666** [comment]
厉害了
