### ISSUE TITLE
Not really sure how to use vue-timeago

### ISSUE THREAD

**Issue by warmjaijai** [egoist/vue-timeago#34]
I would consider myself a beginner and I am trying vue timeago on Laravel 5.3 framework but not seem to work. Not sure it is just me, but I have no idea how to use your lovely invention. Is there any coding example for reference? Does it take all kind of format of data and time and put them into timeago format? Please let me know if I have missed the info somewhere here. Thanks.

**Comment by egoist** [comment]
The value of `:since` prop could be any `dataString`, since it's passed into `new Date(since)`
