### ISSUE TITLE
Watch autoUpdate changes and reinitiate interval

### ISSUE THREAD

**Issue by darklow** [egoist/vue-timeago#37]
Thanks for the great library!

It would be great if it would watch `autoUpdate` and reinitiate update() interval if `autoUpdate` changes. I have a notifications menus with lot of items and these menus can be collapsed (hidden, not destroyed) and it would be great if I could change dynamically autoUpdate from 1 second to something much larger like 60 seconds or disable completely if menu is not visible at the time.

Then I could bind my app `autoUpdate` property to timeago component prop by
`<timago :auto-update="autoUpdate">`.
Thanks.

**Comment by egoist** [comment]
Sounds reasonable, I might add this later and PR welcome 😄
