### ISSUE TITLE
Update vue time ago every time...

### ISSUE THREAD

**Issue by masterpowers** [egoist/vue-timeago#4]
Time ago that uses jquery automatically update based on the time it can either update per secs per minute per hour and perday....

Is this also possible in your repo? 
It would be awesome if the value can be updated depending on the time...

If it less than 60s it will update every secs ....
If less than 60 minutes it will update very minute...
Greater than than 24 hrs it will update  every hour...
If it is greater than 1 day it will update  every day 
And so fort....

Vue time ago act as a filter...

Is there a way i can achieve what im saying to u using vue time ago?

**Comment by egoist** [comment]
It's possible but never looks elegant, you can set an interval to update the original time to achieve this:

```js
setInterval(() => {
  this.time -= 60000
}, 60000)

{{ time || timeago }}
```

So I think implement `vue-timeago` as a directive may be a better solution, it's more powerful than filter, and we can do `switch language on the fly` as well besides what you said.

**Comment by egoist** [comment]
Done, implemented as a component.
