### ISSUE TITLE
Plurals

### ISSUE THREAD

**Issue by Iworb** [egoist/vue-timeago#52]
There's only 2 forms for single/multiple forms, but there's no implementation of [plurals](http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html).

Example: there's 3 plural form for russian language which could be calculated like thatplural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2); But this project doesn't support that kind of plurals.

**Comment by egoist** [comment]
Try v4.
