### ISSUE TITLE
Feature Request: Time "left" ("to go", remaining, etc)

### ISSUE THREAD

**Issue by jezmck** [egoist/vue-timeago#55]
When a negative difference is encountered, we only see "just now", can we please instead get "3 minutes left" or similar?

**Comment by cord** [comment]
The jquery Version http://timeago.yarp.com/ allows future dates, would be great to have vue-timeago supporting this as well.

**Comment by hjoensson** [comment]
This would be really nice to have. The current behavior is almost a bug as future dates are displayed as "just now".

**Comment by benyanke** [comment]
Agreed with this - I was actually hoping this would work for my app which primarily uses future dates, not past ones.

**Comment by egoist** [comment]
It's now supported in vue-timeago v4 which uses date-fns.
