### ISSUE TITLE
我想设置 timeago 的最大值

### ISSUE THREAD

**Issue by lishengzxc** [egoist/vue-timeago#6]
比如：我设置了一个最大值为“月”，如果超过31天，就不在以 timeago 的形式输出了。我自己尝试修改了代码，发现会将你的转换逻辑给全部重写，所以我没提上来，最后想看看你会怎么改~

**Comment by egoist** [comment]
直接 `if (seconds > month) {return ...}` 就行吧

**Comment by lishengzxc** [comment]
这可能会把你的 三元条件语句给 重写了，如果可以的话，我愿意改改看~

**Comment by egoist** [comment]
改成 component 了，你可以 PR 到 dev 分支

- [x] Format time in `xxx ago`
- [ ] Auto update in a period
- [ ] `maxtime`

**Comment by lishengzxc** [comment]
**Switch language without refreshing**，我觉得不是太合适，如果以后语言文件多了，会不会要一起都加载，才能保证无刷新i18n

**Comment by egoist** [comment]
刷新了再切换语言还是要先把需要的语言文件打包进 bundle 文件 😂

**Comment by lishengzxc** [comment]
😂 有道理~ `maxtime` 我写好了 我想把`navigator.language`加到 example 里需要吗？
