### ISSUE TITLE
[question] Is `format` not supported at v4?

### ISSUE THREAD

**Issue by zhandao** [egoist/vue-timeago#77]
请问 v4 不支持 format 了？

**Comment by egoist** [comment]
`format` exists because of [max-time](https://github.com/egoist/vue-timeago/tree/3#max-time) exists, but there does not seem to be many use cases for `max-time` so I removed both, we can sure add it back if needed.

**Comment by zhandao** [comment]
I see.

**Comment by zhandao** [comment]
(At least I need it.)

**Comment by egoist** [comment]
Can you explain your use case?

**Comment by zhandao** [comment]
OK. For UX, I set max-time to half a day, in `format` handler, I render the time (0.5 < time <= 1 days) as: `today 22:45` / `yesterday 18:30`.
