### ISSUE TITLE
autoUpdate expected Number, got String

### ISSUE THREAD

**Issue by bbashy** [egoist/vue-timeago#78]
`[Vue warn]: Invalid prop: type check failed for prop "autoUpdate". Expected Number, got String.`

comes up when using this;
```
<timeago :since="message.created_c" :auto-update="2"></timeago>
```
Surely that passes it as a number? It's not `:auto-update="'2'"`...

**Comment by egoist** [comment]
It's working properly for me: https://codesandbox.io/s/j7x4m7vkpy?module=%2Fsrc%2FApp.vue

**Comment by bbashy** [comment]
It works but in `npm run dev` it warns about it. Not really sure what I'm doing differently. Guess it's not a real issue so thanks for replying!
