### ISSUE TITLE
Custom "convert" function

### ISSUE THREAD

**Issue by nkostadinov** [egoist/vue-timeago#84]
It would be nice if we could provide our custom "convert" function. I also use date-fns but with some edge cases that I handle with custom logic. 
This could be easily done via function prop.

**Comment by egoist** [comment]
In which specific cases do you want a custom `convert` function?

**Comment by egoist** [comment]
#83 might be a use case, PR welcome.

**Comment by egoist** [comment]
Implemented in v5.
