### ISSUE TITLE
Difference between 2 past dates

### ISSUE THREAD

**Issue by AndreGuerra123** [egoist/vue-timeago#86]
Hello, 
It would be nice to have the difference between two past dates (not against current time/Date.now()), such as an elapsed time. For instance, the output would be: "23 min. elapsed.". A prop such as finalDate would be helpful.
Regards, 
Andre

**Comment by egoist** [comment]
You can create a custom converter for this: https://github.com/egoist/vue-timeago/blob/master/README.md#converter
