### ISSUE TITLE
vue-timeago demo

### ISSUE THREAD

**Issue by Zoha** [egoist/vue-timeago#92]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24100%20Funded-%2300A156.svg" />](https://issuehunt.io/r/egoist/vue-timeago/issues/92)

is not better to make a demo for your package?  :|

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $100.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($100.00)
### Submitted pull Requests
- [#98 feat: add demo site](https://issuehunt.io/r/egoist/vue-timeago/pull/98)
- [#99 Add a website](https://issuehunt.io/r/egoist/vue-timeago/pull/99)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/egoist/vue-timeago/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by egoist** [comment]
Yeah, a demo that demonstrates all the options sound nice.
