### ISSUE TITLE
Is there a way to globally change the locale?

### ISSUE THREAD

**Issue by Burtonium** [egoist/vue-timeago#95]
It's not very DRY if I override the locale on every instance. Something like this would be great, but maybe not feasible to have all instances update their props.

`
    VueTimeago.locale = 'ja';
`

**Comment by zek** [comment]
That would be cool 👍

**Comment by raisezhang** [comment]
I also need that~     

Specific case： Vue   &   SSR  &   runInNewContext: false

Thanks ~

**Comment by egoist** [comment]
https://github.com/egoist/vue-timeago#update-locale-globally This may be what you want.
